#!/usr/bin/env bash
# Stamp current git state into lib/version/src/version.ts.
# Runs on every dev start and build via predev/prebuild hooks in each artifact.
# Safe to run from any cwd inside the repo; resolves the repo root via git.

set -euo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo "")"
if [ -z "$ROOT" ]; then
  echo "stamp-version: not inside a git repo, leaving placeholder"
  exit 0
fi

OUT="$ROOT/lib/version/src/version.ts"

COMMIT=$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || echo "0000000000000000000000000000000000000000")
SHORT="${COMMIT:0:7}"
TAG=$(git -C "$ROOT" describe --tags --abbrev=0 2>/dev/null || echo "untagged")
BUILT_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
REPO_URL="https://github.com/bitPOS-app/bitpos"

# Skip write if commit+tag unchanged (avoids dev-loop churn).
# This means builtAt records "first stamped at this commit/tag" rather than
# "this exact rebuild's timestamp" — see comment in lib/version/src/version.ts.
if [ -f "$OUT" ] && grep -q "commit: \"$COMMIT\"" "$OUT" && grep -q "tag: \"$TAG\"" "$OUT"; then
  exit 0
fi

# Atomic write (tmp + mv) so concurrent predev/prebuild from parallel
# workspace packages cannot race and produce a partially-written file.
TMP="$(mktemp "${OUT}.XXXXXX")"
cat > "$TMP" <<EOF
// AUTO-GENERATED by scripts/stamp-version.sh.
// Regenerated on every \`pnpm dev\` / \`pnpm build\` via predev/prebuild hooks.

export interface BitPOSVersion {
  /** Full 40-char commit SHA the running build was compiled from. */
  commit: string;
  /** Short 7-char SHA for display. */
  shortCommit: string;
  /** Latest annotated tag (e.g. "v0.1.0"), or "untagged" if none. */
  tag: string;
  /** ISO-8601 timestamp of when the build was stamped. */
  builtAt: string;
  /** Canonical public repo URL. */
  repoUrl: string;
}

export const version: BitPOSVersion = {
  commit: "$COMMIT",
  shortCommit: "$SHORT",
  tag: "$TAG",
  builtAt: "$BUILT_AT",
  repoUrl: "$REPO_URL",
};
EOF

mv -f "$TMP" "$OUT"
echo "stamp-version: tag=$TAG sha=$SHORT built=$BUILT_AT"
