// AUTO-GENERATED by scripts/stamp-version.sh.
// Regenerated on every `pnpm dev` / `pnpm build` via predev/prebuild hooks.

export interface BitPOSVersion {
  /** Full 40-char commit SHA the running build was compiled from. */
  commit: string;
  /** Short 7-char SHA for display. */
  shortCommit: string;
  /** Latest annotated tag (e.g. "v0.1.0"), or "untagged" if none. */
  tag: string;
  /** ISO-8601 timestamp of when the build was stamped. */
  builtAt: string;
  /** Canonical public repo URL. */
  repoUrl: string;
}

export const version: BitPOSVersion = {
  commit: "c632ab41052e8f03adb72ea9f1850217d654c542",
  shortCommit: "c632ab4",
  tag: "v0.1.0",
  builtAt: "2026-05-24T15:22:26Z",
  repoUrl: "https://github.com/bitPOS-app/bitpos",
};
